// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Ch04_RecordLiterals$LearningTyddReason = require("./Ch04_RecordLiterals.bs.js");

var bobId = Ch04_RecordLiterals$LearningTyddReason.bob[/* id */0];

var bobName = Ch04_RecordLiterals$LearningTyddReason.bob[/* name */1];

var id = Ch04_RecordLiterals$LearningTyddReason.jim[/* id */0];

var jimName = Ch04_RecordLiterals$LearningTyddReason.jim[/* name */1];

var tomId = Ch04_RecordLiterals$LearningTyddReason.tom[/* id */0];

var name = Ch04_RecordLiterals$LearningTyddReason.tom[/* name */1];

var tomName = Ch04_RecordLiterals$LearningTyddReason.tom[/* name */1];

exports.bobId   = bobId;
exports.bobName = bobName;
exports.id      = id;
exports.jimName = jimName;
exports.tomId   = tomId;
exports.name    = name;
exports.tomName = tomName;
/* No side effect */
