// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var jim = /* record */[
  /* id */2,
  /* name */"Jim"
];

var tom = /* record */[
  /* id */3,
  /* name */"Tom"
];

var bob = /* record */[
  /* id */1,
  /* name */"Bob"
];

var tomId = 3;

exports.bob   = bob;
exports.jim   = jim;
exports.tomId = tomId;
exports.tom   = tom;
/* No side effect */
