// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Ch04_RecordLiterals$LearningTyddReason = require("./Ch04_RecordLiterals.bs.js");

var bobLongForm1_000 = /* id */Ch04_RecordLiterals$LearningTyddReason.bob[/* id */0];

var bobLongForm1 = /* record */[
  bobLongForm1_000,
  /* name */"Robert"
];

var bobLongForm2_000 = /* id */Ch04_RecordLiterals$LearningTyddReason.bob[/* id */0];

var bobLongForm2 = /* record */[
  bobLongForm2_000,
  /* name */"Robert"
];

var bob = Ch04_RecordLiterals$LearningTyddReason.bob;

exports.bob          = bob;
exports.bobLongForm1 = bobLongForm1;
exports.bobLongForm2 = bobLongForm2;
/* No side effect */
