// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var bob = /* tuple */[
  1,
  "Bob"
];

var jim = /* tuple */[
  "Jim",
  2
];

exports.bob = bob;
exports.jim = jim;
/* No side effect */
