// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function makePerson(id, name) {
  return /* record */[
          /* id */id,
          /* name */name
        ];
}

exports.makePerson = makePerson;
/* No side effect */
