// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Ch10_PlatformCompany$Ch10final = require("../src/Ch10_PlatformCompany.bs.js");

describe("Platform", (function () {
        Jest.test("list facebook business app", (function (param) {
                var facebook_biz = Ch10_PlatformCompany$Ch10final.Platform[/* apps */0](/* `Facebook */[
                      -480901274,
                      "business"
                    ]);
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "facebook ads (https://www.facebook.com/business)",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](facebook_biz));
              }));
        return Jest.test("instagram number of accounts", (function (param) {
                      var nb = Ch10_PlatformCompany$Ch10final.instagram[/* numberOfAccounts */2];
                      Ch10_PlatformCompany$Ch10final.newSignUp(Ch10_PlatformCompany$Ch10final.instagram);
                      return Jest.Expect[/* toEqual */12](nb + 1 | 0, Jest.Expect[/* expect */0](Ch10_PlatformCompany$Ch10final.instagram[/* numberOfAccounts */2]));
                    }));
      }));

/*  Not a pure module */
