// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function appToString(app) {
  return app[/* name */0] + (" (" + (app[/* url */1] + ")"));
}

function newSignUp(app) {
  app[/* numberOfAccounts */2] = app[/* numberOfAccounts */2] + 1 | 0;
  return /* () */0;
}

var facebook = /* record */[
  /* name */"facebook",
  /* url */"https://facebook.com",
  /* numberOfAccounts */10000
];

var facebookads = /* record */[
  /* name */"facebook ads",
  /* url */"https://www.facebook.com/business",
  /* numberOfAccounts */10000
];

var messenger = /* record */[
  /* name */"messenger",
  /* url */"https://www.facebook.com/messenger",
  /* numberOfAccounts */10000
];

var instagram = /* record */[
  /* name */"instagram",
  /* url */"https://www.instagram.com",
  /* numberOfAccounts */10000
];

var google = /* record */[
  /* name */"google",
  /* url */"https://google.com",
  /* numberOfAccounts */10000
];

var gmail = /* record */[
  /* name */"gmail",
  /* url */"https://google.com/gmail",
  /* numberOfAccounts */10000
];

var googleads = /* record */[
  /* name */"google ads",
  /* url */"https://ads.google.com",
  /* numberOfAccounts */10000
];

var googleplus = /* record */[
  /* name */"google+",
  /* url */"https://plus.google.com",
  /* numberOfAccounts */10000
];

function apps(company) {
  if (typeof company === "number") {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "Ch10_PlatformCompany.re",
            79,
            52
          ]
        ];
  } else {
    var variant = company[0];
    if (variant !== -480901274) {
      if (variant !== 377370585) {
        throw [
              Caml_builtin_exceptions.match_failure,
              /* tuple */[
                "Ch10_PlatformCompany.re",
                79,
                52
              ]
            ];
      } else {
        switch (company[1]) {
          case "business" : 
              return /* :: */[
                      appToString(googleads),
                      /* [] */0
                    ];
          case "social" : 
              return /* :: */[
                      appToString(googleplus),
                      /* [] */0
                    ];
          default:
            throw [
                  Caml_builtin_exceptions.match_failure,
                  /* tuple */[
                    "Ch10_PlatformCompany.re",
                    86,
                    24
                  ]
                ];
        }
      }
    } else {
      switch (company[1]) {
        case "business" : 
            return /* :: */[
                    appToString(facebookads),
                    /* [] */0
                  ];
        case "social" : 
            return /* :: */[
                    appToString(facebook),
                    /* :: */[
                      appToString(messenger),
                      /* :: */[
                        appToString(instagram),
                        /* [] */0
                      ]
                    ]
                  ];
        default:
          throw [
                Caml_builtin_exceptions.match_failure,
                /* tuple */[
                  "Ch10_PlatformCompany.re",
                  81,
                  26
                ]
              ];
      }
    }
  }
}

var Platform = /* module */[/* apps */apps];

exports.appToString = appToString;
exports.newSignUp = newSignUp;
exports.facebook = facebook;
exports.facebookads = facebookads;
exports.messenger = messenger;
exports.instagram = instagram;
exports.google = google;
exports.gmail = gmail;
exports.googleads = googleads;
exports.googleplus = googleplus;
exports.Platform = Platform;
/* No side effect */
