// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function make(id, name) {
  return /* record */[
          /* id */id,
          /* name */$$String.trim($$String.capitalize(name))
        ];
}

var Person = /* module */[/* make */make];

exports.Person = Person;
/* No side effect */
