// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function make(id, name) {
  return /* record */[
          /* id */id,
          /* name */name
        ];
}

var Person = /* module */[/* make */make];

var Company = /* module */[];

exports.Person  = Person;
exports.Company = Company;
/* No side effect */
