// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function greet(person) {
  return "Hello, " + (person[/* name */1] + (" with ID " + (Pervasives.string_of_int(person[/* id */0]) + "!")));
}

exports.greet = greet;
/* No side effect */
