// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var bob = /* record */[
  /* id */1,
  /* name */"Bob"
];

var acmeCo_002 = /* employees : :: */[
  bob,
  /* [] */0
];

var acmeCo = /* record */[
  /* id */1,
  /* name */"Acme Co.",
  acmeCo_002
];

exports.bob    = bob;
exports.acmeCo = acmeCo;
/* No side effect */
