// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var age = "33";

var greeting = "Hello, Bob aged 34";

var name = "Jim";

var greeting2 = "Hello, Jim aged 33";

exports.age       = age;
exports.greeting  = greeting;
exports.name      = name;
exports.greeting2 = greeting2;
/* No side effect */
