// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';


var bobEducation = /* College */1;

var bobPaymentMethod = /* Cash */0;

var jimEducation = /* Other */3;

var jimPaymentMethod = /* PurchaseOrder */["PO-1234"];

exports.bobEducation = bobEducation;
exports.bobPaymentMethod = bobPaymentMethod;
exports.jimEducation = jimEducation;
exports.jimPaymentMethod = jimPaymentMethod;
/* No side effect */
