// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';


var colour = /* Red */4100401;

var angle = /* `degrees */[
  979035047,
  45.0
];

var pressA = /* `keypress */[
  -104560252,
  /* "a" */97
];

exports.colour = colour;
exports.angle = angle;
exports.pressA = pressA;
/* No side effect */
