// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';


function paymentMethodThanks(paymentMethod) {
  if (paymentMethod) {
    return "Thank you for your purchase order # " + paymentMethod[0];
  } else {
    return "Thank you for your cash payment";
  }
}

exports.paymentMethodThanks = paymentMethodThanks;
/* No side effect */
