// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function classifyId(id) {
  if (id >= 6) {
    if (id >= 11) {
      return "High";
    } else {
      return "Medium";
    }
  } else if (id > 0) {
    return "Low";
  } else {
    return "High";
  }
}

function greet1(person) {
  var match = person[/* id */0];
  var match$1 = person[/* name */1];
  if (match$1 === "Dave") {
    return "I'm sorry, Dave, I can't let you do that.";
  } else if (match !== 1) {
    return "Hi, " + (match$1 + (" with ID " + (Pervasives.string_of_int(match) + "!")));
  } else {
    return "Hello, boss.";
  }
}

function greet2(person) {
  var id = person[/* id */0];
  if (person[/* name */1] === "Dave") {
    return "I'm sorry, Dave, I can't let you do that.";
  } else if (id !== 1) {
    return "Hi, " + (person[/* name */1] + (" with ID " + (Pervasives.string_of_int(id) + "!")));
  } else {
    return "Hello, boss.";
  }
}

exports.classifyId = classifyId;
exports.greet1 = greet1;
exports.greet2 = greet2;
/* No side effect */
