// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var optionArr = /* array */[undefined];

var optionRef = /* record */[/* contents */undefined];

exports.optionArr = optionArr;
exports.optionRef = optionRef;
/* No side effect */
