// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

var empty = /* array */[];

var singleton = /* int array */[1];

var multi = /* int array */[
  /* false */0,
  /* true */1,
  /* true */1
];

Caml_array.caml_array_set(multi, 1, /* false */0);

console.log(Caml_array.caml_array_get(multi, 1));

exports.empty = empty;
exports.singleton = singleton;
exports.multi = multi;
/*  Not a pure module */
